{% set version = "0.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-shinycssloaders
  version: {{ version|replace("-", "_") }}

source:
  fn: shinycssloaders_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/shinycssloaders_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/shinycssloaders/shinycssloaders_{{ version }}.tar.gz
  sha256: 8d14ce1eed5cc66c451d4c8b8ca303a6d01128703d0eed0b090d43cb200df8bf

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-digest
    - r-glue
    - r-shiny
  run:
    - r-base
    - r-digest
    - r-glue
    - r-shiny

test:
  commands:
    - $R -e "library('shinycssloaders')"           # [not win]
    - "\"%R%\" -e \"library('shinycssloaders')\""  # [win]

about:
  home: https://github.com/andrewsali/shinycssloaders
  license: GPL-3
  summary: Create a lightweight Shiny wrapper for the css-loaders created by Luke Hass <https://github.com/lukehaas/css-loaders>.
    Wrapping a Shiny output will automatically show a loader when the output is (re)calculating.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
    - halldc
