appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ceDAnp8Ycdssg/KK+cf7gi6Hx3UbQEEksthH3C7TemrTD+Jzko6fz19Nh2EgGfbCJFzW31zOzFpiYaX5VlqtzZNT6wpEQmtdMqYQEcyLAWC/cKxX7nMK/tw1k8Nw3O+uM+lDRXX+fRFsT5QAG+j839m4OJIJ/vUClalowo1xZ7MGFhpLnkMWfYGSVWM0bZx2esBGviQLUwk573t2TbkDcfFeAsw012tRlhrvfaSO0v6eVgyknMBRn351rWIJLCFdVVkEM3ALm6vnRwgpagH4MoK7kBgqSFf6xoAHA4OdPCY70nWFNT1Zo8Q4r+8NUZbrsCmJoK57tBDVQH7pAAZ2M9xUYaU1JAKdbUK52fT7+y/di7F3vRSsMqsVPhFj/ol4TYzqVdzN6/jeKg3QG8XAdnB7hRcb0BtSZYa3TrYk5fGYeaNtumCjrJ2eH7Sv0mygAVDb8k68lh7zUPwyqWwJfu7YlrWy51of3g7kratRXuCLhISKcIvhjf3E/6/dM18rNwgZMl+rH1kLXkGONgZousRcFPIvL02e2lyhZBoYxOoXPWOqbkEtLM/3JdfsqS+qpz6A08ODQHq9dtVGT9IDpaHfYvP6FsoBL1UdP8WylvL37AriCc5S+tTcRbKmjYVNGuCCyo1cO50gCiQN50Qtv4Epk7yBV51kqQhf/vGMPRo=}
