travis:
  secure:
    BINSTAR_TOKEN: LkzQQhQIhQskEQp1nJNIYXn2JoRN4mj7l7vUoPWAYH8OKoP/48B9GCpTfFM1j7n1JL2KrtV4kw037ZnsvNVZn0wmb7B5kIWxXbGAHomXQktBGVgaQH6S6DyX4rFxt6W/3GZRzAj/YZHO1NLvzdyzXFeA9+XOdNO/6G+h2dsjo+QUbc69izhju2HhGT/LZUj/ZOS85HBWoJECjofQSnVyFwMj/kcX2bKA98Ty6DZx4IkHRGN2vNe39vViL8rb2esuQjbu54cMO4/rrVVqRAuSTxTAwJGNFA7NAhiADOHc21ZtrG88jp//OkW9RSHHbe2uIFgJKDTvYyioW+VDui41Leq2r225JCwZFE6sZ7QYJmriie5rxH02AxzPYj2FppvTZ4dzvVp47Kn7DvF/P+pJRAhTpnZEfDEXHTErT/uFH970LqLTzJuy7R3mKhgvx47YNW8kSVKJp63xTM39Kkzg7Cqr7mN1GRT5LoPjVtBhwMvzO7s2RlKIXmsls36D/mUFl9PRynv0cRzb+1ChUa8gvtDaul3EaOPANaPjA3eVy1uhGrYcYNLE3zDVBXxjBWNyifBd6L5hhV9vFU4u8JvHqsXl35jtdvLVceLQOHq4dckSiPBvf2SOke5Q6oVvi3/nC2XotaQn7gCd8O3Q58WkUc4glbkwVKpLq7GPMjao4NE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
